const privilegesValues = [
  { id: 'delete', value: 'delete' },
  { id: 'deleteIdentities', value: 'deleteIdentities' },
  { id: 'deleteMetaroles', value: 'deleteMetaroles' },
  { id: 'deletePreferences', value: 'deletePreferences' },
  { id: 'deletePrivileges', value: 'deletePrivileges' },
  { id: 'deleteRealms', value: 'deleteRealms' },
  { id: 'deleteRoles', value: 'deleteRoles' },
  { id: 'get', value: 'get' },
  { id: 'getIdentities', value: 'getIdentities' },
  { id: 'getMetaroles', value: 'getMetaroles' },
  { id: 'getPrivileges', value: 'getPrivileges' },
  { id: 'getRealms', value: 'getRealms' },
  { id: 'getRoles', value: 'getRoles' },
  { id: 'getSelfRealms', value: 'getSelfRealms' },
  { id: 'getServiceConfig', value: 'getServiceConfig' },
  { id: 'list', value: 'list' },
  { id: 'listIdentities', value: 'listIdentities' },
  { id: 'listMetaroles', value: 'listMetaroles' },
  { id: 'listPrivileges', value: 'listPrivileges' },
  { id: 'listRealms', value: 'listRealms' },
  { id: 'listRoles', value: 'listRoles' },
  { id: 'manage', value: 'manage' },
  { id: 'manageIdentities', value: 'manageIdentities' },
  { id: 'manageMetaroles', value: 'manageMetaroles' },
  { id: 'managePreferences', value: 'managePreferences' },
  { id: 'managePrivileges', value: 'managePrivileges' },
  { id: 'manageRealms', value: 'manageRealms' },
  { id: 'manageRoles', value: 'manageRoles' },
  { id: 'manageServiceConfig', value: 'manageServiceConfig' },
  { id: 'operate', value: 'operate' },
  { id: 'post', value: 'post' },
  { id: 'postIdentities', value: 'postIdentities' },
  { id: 'postMetaroles', value: 'postMetaroles' },
  { id: 'postPreferences', value: 'postPreferences' },
  { id: 'postPrivileges', value: 'postPrivileges' },
  { id: 'postRealms', value: 'postRealms' },
  { id: 'postRoles', value: 'postRoles' },
  { id: 'put', value: 'put' },
  { id: 'putIdentities', value: 'putIdentities' },
  { id: 'putMetaroles', value: 'putMetaroles' },
  { id: 'putPreferences', value: 'putPreferences' },
  { id: 'putPrivileges', value: 'putPrivileges' },
  { id: 'putRealms', value: 'putRealms' },
  { id: 'putRoles', value: 'putRoles' },
  { id: 'putSelfRealms', value: 'putSelfRealms' },
  { id: 'putServiceConfig', value: 'putServiceConfig' },
  { id: 'read', value: 'read' },
  { id: 'readIdentities', value: 'readIdentities' },
  { id: 'readMetaroles', value: 'readMetaroles' },
  { id: 'readPrivileges', value: 'readPrivileges' },
  { id: 'readRealms', value: 'readRealms' },
  { id: 'readRoles', value: 'readRoles' },
  { id: 'renewJwtKeys', value: 'renewJwtKeys' },
  { id: 'selfManagement', value: 'selfManagement' },
];

export {
  privilegesValues,
};
