const VALID_REFRESH_SCOPES = [
  'productlist',
  'catalogs',
  'stores',
  'orderlist',
  'notifications',
  'notification-definition',
  'notification-history',
  'carts',
  'licenses',
  'recommendations',
  'marketingAbandoned',
  'resellers',
  'customerslist',
  'marketingCampaigns',
  'discounts',
  'emailbuilder',
  'discountrules',
  'roles',
  'metaRoles',
  'privileges',
  'remittables',
  'audits',
  'onboarding',
  'translations',
  'invoicetranslations',
  'users',
  'realms',
];
const VALID_FILTER_SCOPES = [
  'productlist',
  'catalogs',
  'stores',
  'subscriptions',
  'licenses',
  'themes',
  'layouts',
  'fonts',
  'translations',
  'orderlist',
  'notifications',
  'notification-definition',
  'notification-history',
  'carts',
  'prices',
  'pricefunctions',
  'autoFulfillments',
  'manualFulfillments',
  'marketingCampaigns',
  'discounts',
  'licenseProviderDefinitions',
  'recommendations',
  'marketingAbandoned',
  'resellers',
  'enduserlist',
  'customerslist',
  'emailbuilder',
  'discountrules',
  'roles',
  'metaRoles',
  'privileges',
  'remittables',
  'audits',
  'onboarding',
  'invoicetranslations',
  'users',
  'realms',
];

const KNOWN_REALMS = ['/nexway', '/mynexway', '/kasperskyfrance'];

const VALID_SEARCH_SCOPES = [
  'orderlist',
  'subscriptions',
  'licenses',
  'carts',
  'stores',
  'productlist',
  'prices',
  'recommendations',
  'discountrules',
  'marketingCampaigns',
  'marketingAbandoned',
  'enduserlist',
  'endusergroups',
  'resellers',
  'realms',
];

export {
  VALID_REFRESH_SCOPES, VALID_FILTER_SCOPES, KNOWN_REALMS, VALID_SEARCH_SCOPES,
};
