const general = {
  welcomeMessage:
    'Hella narwhal Cosby sweater McSweeneys, salvia kitsch before they sold out.',
  lightMode: 'Light mode',
  darkMode: 'Dark mode',
  error: 'Something went wrong! Please try again later!',
  filters: 'Filters',
  reset: 'Reset',
  resetPassword: 'Reset password',
  resetPasswordMessage: 'Please use your work email to reset your password.',
  setNewPassword: 'Set new password',
  javascriptMasterEchovoxUA: 'Javascript Master @ EchovoxUA',
  checkYourEmailToResetThePassword: 'Check your email to reset the password',
  noResults: 'No results',
  first: 'First',
  last: 'Last',
  next: 'Next',
  passwordUpdated: 'Password Updated!',
  itemURLHasBeenCopied: 'Item URL has been copied!',
  welcomeBack: 'Welcome back',
  sessionEnded: 'Session ended!',
  identity: 'Identity',
  order: 'Order',
  product: 'Product',
  store: 'Store',
  hasBeenSuccessfullyDeleted: ' has been successfully deleted!',
  updatesHaveBeenSaved: 'Updates have been saved!',
  selectImage: ' Select image',
  features: ' Features',
  live: 'Live',
  test: ' Test',
  payment: 'Payment',

};

export default general;
