const sections = {
  orderlist: 'Order List',
  orders: 'Orders',
  subscriptions: 'Subscriptions',
  invoices: 'Invoices',
  licenses: 'Licenses',
  carts: 'Carts',
  archivedorders: 'Archived Orders',
  stores: 'Stores',
  checkoutpagebuilder: 'Checkout Page Builder',
  storesetup: 'Store Setup',
  themes: 'Themes',
  layouts: 'Layouts',
  fonts: 'Fonts',
  localization: 'Localization',
  translations: 'Translations',
  invoicetranslations: 'Invoice Translations',
  emailbuilder: 'Email Builder',
  productlist: 'Product List',
  products: 'Products',
  pricemodels: 'Price Models',
  prices: 'Prices',
  pricefunctions: 'Price Functions',
  recommendations: 'Recommendations',
  fulfillment: 'Fulfillment Packages',
  autoFulfillments: 'Auto Fulfillments',
  manualFulfillments: 'Manual Fulfillments',
  licenseProviderDefinitions: 'License Provider Definitions',
  catalogs: 'Catalogs',
  marketing: 'Marketing',
  discountrules: 'Discount Rules',
  campaigns: 'Campaigns',
  marketingCampaigns: 'Marketing Campaigns',
  marketingAbandoned: 'Marketing Abandoned',
  endusers: 'End-Users',
  enduserlist: 'End-User List',
  endusergroups: 'End-User Groups',
  resellers: 'Resellers',
  reports: 'Reports',
  settings: 'Settings',
  users: 'Users',
  userroles: 'User Roles & Profiles',
  roles: 'Roles',
  metaRoles: 'Meta Roles',
  privileges: 'Privileges',
  notifications: 'Notifications',
  'notification-definition': 'Notification Definition',
  'notification-history': 'Notification History',
  myaccount: 'My Account',
  customermanagement: 'Customer Management',
  customerslist: 'Customers List',
  onboarding: 'Onboarding',
  remittables: 'Remittables',
  audits: 'Audits',
  sales: 'Sales',
  businessAnalysis: 'Business Analysis',
};

export default sections;
