const sideBar = {
  subheaders: {
    orders: 'Orders',
    storeSetup: 'Store Setup',
    products: 'Products',
    marketing: 'Marketing',
    customers: 'Customers',
    settings: 'Settings',
    clientManagement: 'Client Management',
    help: 'Help',
  },
  titles: {
    dashboard: 'Dashboard',
    products: 'Products',
    stores: 'Stores',
    orders: 'Orders',
    archivedOrders: 'Archived Orders',
    invoicesCreditNotes: 'Invoices / Credit Notes',
    subscriptions: 'Subscriptions',
    salesCustomers: 'Sales & customers',
    customers: 'Customers',
    customerGroups: 'Customer Groups',
    resellers: 'Resellers',
    marketing: 'Marketing',
    checkoutExperience: 'Checkout Page Builder',
    reports: 'Reports',
    myAccount: 'My Account',
    api: 'API',
    servicesConfiguration: 'Services Configuration',
    administration: 'Administration',
    identities: 'Identities',
    notification: 'Notifications',
    licenses: 'Licenses',
    carts: 'Carts',
    localization: 'Localization',
    emailBuilder: 'Email Builder',
    priceModels: 'Price Models',
    crosSellUpSellReco: 'Crossell Upsell Recommendations',
    fulfillmentPackages: 'Fulfillment packages',
    discountRules: 'Discount rules',
    campaigns: 'Campaigns',
    users: 'Users',
    userPrivileges: 'User Privileges',
    userRolesProfiles: 'User Roles & Profiles',
    eventNotifications: 'Event Notifications',
    clients: 'Clients',
    onboarding: 'Onboarding',
    remittables: 'Remittables',
    audits: 'Audits',
    apiDocumentation: 'API Documentation',
    productDocumentation: 'Product Documentation',
  },
};

export default sideBar;
