const countriesOptions = [
  { id: 'AD', value: 'Andorra' },
  { id: 'AE', value: 'United Arab Emirates' },
  { id: 'AF', value: 'Afghanistan' },
  { id: 'AG', value: 'Antigua and Barbuda' },
  { id: 'AI', value: 'Anguilla' },
  { id: 'AL', value: 'Albania' },
  { id: 'AM', value: 'Armenia' },
  { id: 'AO', value: 'Angola' },
  { id: 'AQ', value: 'Antarctica' },
  { id: 'AR', value: 'Argentina' },
  { id: 'AS', value: 'American Samoa' },
  { id: 'AT', value: 'Austria' },
  { id: 'AU', value: 'Australia' },
  { id: 'AW', value: 'Aruba' },
  { id: 'AX', value: 'Alland Islands' },
  { id: 'AZ', value: 'Azerbaijan' },
  { id: 'BA', value: 'Bosnia and Herzegovina' },
  { id: 'BB', value: 'Barbados' },
  { id: 'BD', value: 'Bangladesh' },
  { id: 'BE', value: 'Belgium' },
  { id: 'BF', value: 'Burkina Faso' },
  { id: 'BG', value: 'Bulgaria' },
  { id: 'BH', value: 'Bahrain' },
  { id: 'BI', value: 'Burundi' },
  { id: 'BJ', value: 'Benin' },
  { id: 'BL', value: 'Saint Barthelemy' },
  { id: 'BM', value: 'Bermuda' },
  { id: 'BN', value: 'Brunei Darussalam' },
  { id: 'BO', value: 'Bolivia' },
];
export default countriesOptions;
