const general = {
  welcomeMessage: 'Hella narwhal Cosby sweater McSweeneys, salvia kitsch before they sold out.',
  lightMode: 'Light mode',
  darkMode: 'Dark mode',
  error: 'Something went wrong! Please try again later!',
  filters: 'Filters',
  reset: 'Reset',
  resetPassword: 'Reset password',
  resetPasswordMessage: 'Please use your work email to reset your password.',
  setNewPassword: 'Set new password',
  javascriptMasterEchovoxUA: 'Javascript Master @ EchovoxUA',
  checkYourEmailToResetThePassword: 'Check your email to reset the password',
  noResults: 'No results',
  first: 'First',
  last: 'Last',
  next: 'Next',
  passwordUpdated: 'Password Updated!',
  itemURLHasBeenCopied: 'Item URL has been copied!',
  welcomeBack: 'Welcome back',
  sessionEnded: 'Session ended!',
  identity: 'Identity',
  order: 'Order',
  notificationDefinition: 'Notification-definition',
  product: 'Product',
  store: 'Store',
  recommendation: 'Recommendation',
  discount: 'Discount',
  price: 'Price',
  hasBeenSuccessfullyDeleted: ' has been successfully deleted!',
  updatesHaveBeenSaved: 'Updates have been saved!',
  selectImage: ' Select image',
  features: ' Features',
  live: 'Live',
  test: ' Test',
  payment: 'Payment',
  translation: 'Translation',
  theme: 'Theme',
  font: 'Font',
  layout: 'Layout',
  checkout: 'Checkout',
  save: 'Save',
  add: 'Add',
  noPackagesFound: 'No packages found',
  addProduct: 'Add Product',
  addPrice: 'Add Price',
  addRecommendation: 'Add Recommendation',
  addCampaign: 'Add Campaign',
  noAvailableOptions: 'No available options',
  marketingNameMandatory: 'Marketing name is mandatory for the default language.',
  noCustomer: 'No customer selected',
  selectCustomer: 'Please select a customer which will own the created resource.',
  itemHasBeenCopied: 'Item Has Been Copied',
  campaign: 'Campaign',
  new: 'New',
  selectNoSourceMeans: 'Select no source means the same as "all sources are selected"',
  role: 'role',
  customer: 'Customer',
  metaRole: 'Meta-Role',
  logoCenter: 'Center.',
  subscription: 'Subscription',
  privileges: {
    general: 'General',
    createdate: 'Create date',
    lastupdate: 'Last update',
    lastupdatereason: 'Last update reason',
    servicename: 'Service name',
    availableactions: 'Available actions',
  },
  keyHasBeenAdded: 'Key Has Been Added',
  keyHasBeenRemoved: 'Key Has BeenRemoved',
  noResourcesMatchCriteria: 'No resources match criteria',
  typeOfIdentity: 'The type of identity is choosen at creation and cannot be modified afterwards. Choose "User" to declare a human agent, and "Application"to obtain credentials for your bots accessing Monetize services.',
  maxNumberOfSecretKeys: 'The maximum number of secret keys is 5',
  listOfIdentityCustomers: 'This is the list of customers this identity is allowed to manage, in addition to the customer owning this identity.',
  selectFiles: 'Select files from your computer or click to enter custom URL',
  uploadFiles: ' upload files',
  privilege: 'privilege',
  notificationEnabled: 'Enabled',
  notificationDisabled: 'Disabled',
  notification: 'Notification',
  rowsPerPage: 'Rows per page',
  findColumn: 'Find column',
  hideAll: 'Hide All',
  showAll: 'Show All',
};

export default general;
