const general = {
  welcomeMessage:
    'Hella narwhal Cosby sweater McSweeneys, salvia kitsch before they sold out.',
  lightMode: 'Mode lumière',
  darkMode: 'Mode sombre',
  error: 'Something went wrong! Please try again later!',
  filters: 'Filters',
  reset: 'Reset',
  resetPassword: 'Reset password',
  resetPasswordMessage: 'Please use your work email to reset your password.',
  setNewPassword: 'Set new password',
  javascriptMasterEchovoxUA: 'Javascript Master @ EchovoxUA',
  checkYourEmailToResetThePassword: 'Check your email to reset the password',
  noResults: 'No results',
  first: 'First',
  last: 'Last',
  next: 'Next',
  passwordUpdated: 'Password Updated!',
  itemURLHasBeenCopied: 'Item URL has been copied!',
  welcomeBack: 'Welcome back',
  sessionEnded: 'Session ended!',
  identity: 'Identity',
  order: 'Order',
  product: 'Product',
  store: 'Store',
  recommendation: 'Recommendation',
  discount: 'Discount',
  hasBeenSuccessfullyDeleted: ' has been successfully deleted!',
  updatesHaveBeenSaved: 'Updates have been saved!',
  selectImage: ' Select image',
  features: ' Features',
  live: 'Live',
  test: ' Test',
  payment: 'Payment',
  translation: 'Translation',
  theme: 'Theme',
  font: 'Font',
  layout: 'Layout',
  checkout: 'Checkout',
  save: 'Save',
  add: 'Add',
  noPackagesFound: 'No packages found',
  addProduct: 'Add Product',
  addCampaign: 'Add Campaign',
  noAvailableOptions: 'No available options',
  marketingNameMandatory:
    'Marketing name is mandatory for the default language.',
  itemHasBeenCopied: 'Item Has Been Copied',
  selectCustomer:
    'Please select a customer which will own the created resource.',
  campaign: 'Campaign',
  price: 'Price',
  new: 'New',
  selectNoSourceMeans:
    'Select no source means the same as "all sources are selected"',
  role: 'role',
  customer: 'Customer',
  metaRole: 'Meta-Role',
  subscription: 'Subscription',
  keyHasBeenAdded: 'Key Has Been Added',
  keyHasBeenRemoved: 'Key Has BeenRemoved',
  noResourcesMatchCriteria: 'No resources match criteria',
  typeOfIdentity: 'The type of identity is choosen at creation and cannot be modified afterwards. Choose "User" to declare a human agent, and "Application"to obtain credentials for your bots accessing Monetize services.',
  maxNumberOfSecretKeys: 'The maximum number of secret keys is 5',
  listOfIdentityCustomers: 'This is the list of customers this identity is allowed to manage, in addition to the customer owning this identity.',
  selectFiles: 'Select files from your computer or click to enter custom URL',
  uploadFiles: ' upload files',
  notification: 'Notification',

};

export default general;
