const labels = {
  creationDate: 'Creation Date',
  lastUpdate: 'Last Update',
  name: 'Name',
  publisherRefID: 'Publisher Ref ID',
  type: 'Type',
  software: 'Software',
  games: 'Games',
  casual: 'Casual',
  service: 'Service',
  b2B: 'B2B',
  b2C: 'B2C',
  status: 'Status',
  enabled: 'Enabled',
  disabled: 'Disabled',
  paymentType: 'Payment Type',
  storeID: 'Store ID',
  iD: 'ID',
  customer: 'Customer',
  amount: 'Amount',
  store: 'Store',
  paymentID: 'Payment ID',
  paymentStatus: 'Payment Status',
  fraudStatus: 'Fraud Status',
  fulfillment: 'Fulfillment',
  subscription: 'Subscription',
  email: 'Email ',
  onlineStore: 'Online Store',
  companyName: 'Company Name',
  orderID: 'Order ID',
  invoiceID: 'InvoiceID',
  currency: 'Currency',
  products: 'Products',
  country: 'Country',
  sellingStores: 'Selling Stores',
  lifeTime: 'Life Time',
  trialAllowed: 'Trial Allowed',
  totalPrice: 'Total Price',
  total: 'Total',
  fullName: 'Full Name',
  userID: ' User ID',
  accountCreated: 'Account Created',
  productID: 'Product ID',
  family: 'Family',
  priceFunction: 'Price function',
  hostnames: 'Hostnames',
  defaultLanguage: 'Default Language',
  salesLanguages: 'Sales Languages',
  enduserPortalTheme: 'Enduser Portal Theme',
  checkoutTheme: 'Checkout theme',
  paymentMethods: 'Payment methods',
  gtmId: 'GTM ID',
  updateReason: 'Update Reason',
  emailDate: 'Email Date',
  invoiceDate: 'Invoice Date',
  endUser: 'End User',
  address: 'Address',
  zipCode: 'Zip Code',
  transactionID: 'Transaction ID',
  installments: 'Installments',
  paymentDeadline: 'Payment Deadline',
};

export default labels;
